sudo: required
services:
  - docker

before_install:
  - docker build -t vzaicevs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vzaicevs/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-599517085082"
  bucket_path: "reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

