sudo: required
services:
  - docker

before_install:
  - docker build -t vzaicevs/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vzaicevs/docker-react npm run test -- --coverage  
